"""
INT8 Quantization & C++ Header Generator for ESP32-CAM
Cognitive CanSat & TinyML Vision Platform
------------------------------------------------------
Quantizes trained PyTorch weights into 8-bit integer tables (INT8)
and auto-generates firmware/esp32_cam_airborne/model_data.h for direct
compilation in Arduino IDE on the ESP32-CAM microcontroller.
"""

import os
import sys
import numpy as np
import torch

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CANDIDATE_PATHS = [
    os.path.join(REPO_ROOT, "ml", "saved_models", "tinylandingnet_best.pth"),
    os.path.join(REPO_ROOT, "ml", "saved_models", "tinyml_landing_safety.pth")
]
MODEL_PATH = next((p for p in CANDIDATE_PATHS if os.path.exists(p)), CANDIDATE_PATHS[0])
FIRMWARE_HEADER = os.path.join(REPO_ROOT, "firmware", "esp32_cam_airborne", "model_data.h")
SAVED_HEADER = os.path.join(REPO_ROOT, "ml", "saved_models", "model_data.h")

def quantize_tensor(tensor: torch.Tensor):
    arr = tensor.detach().cpu().numpy()
    max_val = np.max(np.abs(arr))
    if max_val == 0:
        scale = 1.0
        q_arr = np.zeros_like(arr, dtype=np.int8)
    else:
        scale = max_val / 127.0
        q_arr = np.clip(np.round(arr / scale), -128, 127).astype(np.int8)
    return q_arr, float(scale)

def generate_header():
    print("=" * 65)
    print(" TinyML INT8 Model Quantization & C++ Header Generator")
    print(" Target: AI-Thinker ESP32-CAM Microcontroller")
    print("=" * 65)

    if not os.path.exists(MODEL_PATH):
        print(f"[ERROR] Trained model weights not found at:\n  {MODEL_PATH}")
        print("Please run 'python ml/train_tinyml_vision.py' first.")
        sys.exit(1)

    print(f"[1/3] Loading PyTorch weights from {MODEL_PATH} ...")
    weights = torch.load(MODEL_PATH, map_location="cpu")

    total_params = 0
    total_bytes = 0
    lines = []

    lines.append("// ============================================================================")
    lines.append("//  TINYML AERIAL LANDING SAFETY VISION MODEL (INT8 QUANTIZED WEIGHTS)")
    lines.append("//  Auto-generated by ml/export_tinyml_header.py")
    lines.append("//  Architecture: TinyLandingNet (Depthwise Separable CNN)")
    lines.append("// ============================================================================\n")
    lines.append("#ifndef MODEL_DATA_H")
    lines.append("#define MODEL_DATA_H\n")
    lines.append("#include <stdint.h>\n")

    lines.append("// Safe Landing Area Index (SLAI) Class Definitions")
    lines.append("enum SLAI_Class {")
    lines.append("    SLAI_SAFE_LZ = 0,          // Clear field, crops, grass (Safe landing)")
    lines.append("    SLAI_OBSTACLE_CANOPY = 1,  // Forest, tree canopy (Entanglement hazard)")
    lines.append("    SLAI_CRITICAL_HAZARD = 2,  // Highway, industrial, residential (Crash hazard)")
    lines.append("    SLAI_WATER_HAZARD = 3      // River, sea, lake (Drowning hazard)")
    lines.append("};\n")

    print("[2/3] Quantizing convolutional filters and linear weights to INT8...")

    for key, val in weights.items():
        clean_name = key.replace(".", "_")
        q_arr, scale = quantize_tensor(val)
        flat_arr = q_arr.flatten()
        
        total_params += flat_arr.size
        total_bytes += flat_arr.nbytes

        shape_str = "_".join(str(s) for s in val.shape)
        lines.append(f"// Layer: {key} (Shape: {val.shape}, Scale: {scale:.6e})")
        lines.append(f"static const float {clean_name}_scale = {scale:.8e}f;")
        lines.append(f"static const int8_t {clean_name}[{flat_arr.size}] = {{")

        # Format 16 bytes per line
        chunk_size = 16
        for i in range(0, flat_arr.size, chunk_size):
            chunk = flat_arr[i:i+chunk_size]
            byte_strs = [f"{int(b):4d}" for b in chunk]
            lines.append("    " + ", ".join(byte_strs) + ",")

        lines.append("};\n")

    lines.append(f"// Model Statistics")
    lines.append(f"#define MODEL_PARAM_COUNT {total_params}")
    lines.append(f"#define MODEL_FLASH_BYTES {total_bytes}")
    lines.append(f"#define INPUT_WIDTH 64")
    lines.append(f"#define INPUT_HEIGHT 64")
    lines.append(f"#define NUM_SLAI_CLASSES 4\n")
    lines.append("#endif // MODEL_DATA_H\n")

    print(f"[3/3] Writing header to firmware directories...")
    header_content = "\n".join(lines)

    for out_path in [FIRMWARE_HEADER, SAVED_HEADER]:
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(header_content)
        print(f"[OK] Generated: {out_path}")

    kb_size = total_bytes / 1024.0
    print("-" * 65)
    print(f"Total INT8 Parameters   : {total_params:,}")
    print(f"Total Flash Storage     : {kb_size:.2f} KB (Well within ESP32 4MB limit)")
    print(f"SRAM Memory Requirement : < 40 KB (Fits effortlessly in internal 520KB SRAM)")
    print("=" * 65)
    print("[SUCCESS] C++ header model_data.h is 100% ready for ESP32-CAM firmware compilation!")

if __name__ == "__main__":
    generate_header()
